name: postgres_crdt
description: Dart implementation of Conflict-free Replicated Data Types (CRDTs) using PostgreSQL
version: 2.1.7
homepage: https://github.com/cachapa/postgres_crdt
repository: https://github.com/cachapa/postgres_crdt
issue_tracker: https://github.com/cachapa/postgres_crdt/issues

environment:
  sdk: ^3.0.0

dependencies:
  postgres: ^3.0.8
  sql_crdt: ^2.1.7
#    path: ../sql_crdt

dev_dependencies:
  lints: any
  test: any
